### ISSUE TITLE
Crash: NullPointerException: Cannot invoke "String.length()" because "this.input" is null

### ISSUE THREAD

**Issue by alwa** [unclebob/more-speech#22]
Version used: 2022-08-14

``` 
id-mismatch "wss://relay.damus.io" computed-id "78b5d35ab6a38bafa22c281d97d638f12677df007e4401ff32d7e5e8d0f12e10" ["EOSE" "more-speech"]
close "wss://relay.damus.io" 1006 ""
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "String.length()" because "this.input" is null
        at java.base/java.net.URI$Parser.parse(URI.java:3165)
        at java.base/java.net.URI.<init>(URI.java:623)
        at clojure.java.browse$open_url_in_browser.invokeStatic(browse.clj:50)
        at clojure.java.browse$browse_url.invokeStatic(browse.clj:74)
        at clojure.java.browse$browse_url.invoke(browse.clj:66)
        at more_speech.ui.swing.main_window$open_link.invokeStatic(main_window.clj:32)
        at more_speech.ui.swing.main_window$open_link.invoke(main_window.clj:30)
        at seesaw.event$fire.invokeStatic(event.clj:263)
        at seesaw.event$fire.invoke(event.clj:262)
        at seesaw.event$fn$reify__10728.hyperlinkUpdate(event.clj:290)
        at java.desktop/javax.swing.JEditorPane.fireHyperlinkUpdate(JEditorPane.java:401)
        at seesaw.core.proxy$javax.swing.JEditorPane$Tag$fd407141.fireHyperlinkUpdate(Unknown Source)
        at java.desktop/javax.swing.text.html.HTMLEditorKit$LinkController.activateLink(HTMLEditorKit.java:905)
        at java.desktop/javax.swing.text.html.HTMLEditorKit$LinkController.mouseClicked(HTMLEditorKit.java:701)
        at java.desktop/java.awt.AWTEventMulticaster.mouseClicked(AWTEventMulticaster.java:278)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6629)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
        at seesaw.core.proxy$javax.swing.JEditorPane$Tag$fd407141.processMouseEvent(Unknown Source)
        at java.desktop/java.awt.Component.processEvent(Component.java:6391)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at seesaw.core.proxy$javax.swing.JEditorPane$Tag$fd407141.processEvent(Unknown Source)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4584)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by unclebob** [comment]
It looks like you must have clicked on a link. Do you know what message that was?  The id of that message would be useful.

**Comment by alwa** [comment]
> Do you know what message that was?

I'm afraid not. I just blindly clicked around (still trying to figure out how it can be useful to me)

**Comment by unclebob** [comment]
Try it again.  I've surrounded that part of the code with a catch block so it shouldn't crash anymore.  It will print a nice error message and you can report that back to me if you get it.  I'm closing this issue now, if you see the problem again, open a new issue.
