### ISSUE TITLE
Crash: InvocationTargetException / NumberFormatException: For input string: "no" under radix 16

### ISSUE THREAD

**Issue by alwa** [unclebob/more-speech#23]
Version used: 2022-08-21

Steps to reproduce: I just fired up the client and this happened:

`Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1369)
        at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1344)
        at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
        at seesaw.invoke$invoke_now_STAR_.invokeStatic(invoke.clj:21)
        at seesaw.invoke$invoke_now_STAR_.doInvoke(invoke.clj:16)
        at clojure.lang.RestFn.invoke(RestFn.java:410)
        at more_speech.ui.swing.main_window.seesawHandler.handle_text_event(main_window.clj:18)
        at more_speech.data_storage$load_events.invokeStatic(data_storage.clj:68)
        at more_speech.data_storage$load_events.invoke(data_storage.clj:64)
        at more_speech.data_storage$read_in_last_n_days.invokeStatic(data_storage.clj:146)
        at more_speech.data_storage$read_in_last_n_days.invoke(data_storage.clj:130)
        at more_speech.core$_main.invokeStatic(core.clj:34)
        at more_speech.core$_main.doInvoke(core.clj:25)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at more_speech.core.main(Unknown Source)
Caused by: java.lang.NumberFormatException: For input string: "no" under radix 16
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Integer.parseInt(Integer.java:668)
        at more_speech.nostr.util$hex_string__GT_bytes$fn__8482.invoke(util.clj:34)
        at clojure.core$map$fn__5884.invoke(core.clj:2759)
        at clojure.lang.LazySeq.sval(LazySeq.java:42)
        at clojure.lang.LazySeq.seq(LazySeq.java:51)
        at clojure.lang.RT.seq(RT.java:535)
        at clojure.lang.Numbers.byte_array(Numbers.java:1397)
        at more_speech.nostr.util$hex_string__GT_bytes.invokeStatic(util.clj:35)
        at more_speech.nostr.util$hex_string__GT_bytes.invoke(util.clj:29)
        at more_speech.nostr.util$hex_string__GT_num.invokeStatic(util.clj:41)
        at more_speech.nostr.util$hex_string__GT_num.invoke(util.clj:38)
        at more_speech.ui.formatters$lookup_reference.invokeStatic(formatters.clj:98)
        at more_speech.ui.formatters$lookup_reference.invoke(formatters.clj:90)
        at clojure.core$partial$fn__5857.invoke(core.clj:2628)
        at clojure.core$mapv$fn__8468.invoke(core.clj:6914)
        at clojure.core.protocols$fn__8181.invokeStatic(protocols.clj:168)
        at clojure.core.protocols$fn__8181.invoke(protocols.clj:124)
        at clojure.core.protocols$fn__8136$G__8131__8145.invoke(protocols.clj:19)
        at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
        at clojure.core.protocols$fn__8166.invokeStatic(protocols.clj:75)
        at clojure.core.protocols$fn__8166.invoke(protocols.clj:75)
        at clojure.core.protocols$fn__8110$G__8105__8123.invoke(protocols.clj:13)
        at clojure.core$reduce.invokeStatic(core.clj:6830)
        at clojure.core$mapv.invokeStatic(core.clj:6905)
        at clojure.core$mapv.invoke(core.clj:6905)
        at more_speech.ui.formatters$replace_references.invokeStatic(formatters.clj:85)
        at more_speech.ui.formatters$replace_references.invoke(formatters.clj:80)
        at more_speech.ui.formatters$format_header.invokeStatic(formatters.clj:48)
        at more_speech.ui.formatters$format_header.invoke(formatters.clj:45)
        at more_speech.ui.swing.article_tree$render_event.invokeStatic(article_tree.clj:137)
        at more_speech.ui.swing.article_tree$render_event.invoke(article_tree.clj:125)
        at seesaw.cells$default_tree_cell_renderer$fn__10929.invoke(cells.clj:44)
        at seesaw.cells.proxy$javax.swing.tree.DefaultTreeCellRenderer$ff19274a.getTreeCellRendererComponent(Unknown Source)
        at java.desktop/javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler.getNodeDimensions(BasicTreeUI.java:3223)
        at java.desktop/javax.swing.tree.AbstractLayoutCache.getNodeDimensions(AbstractLayoutCache.java:497)
        at java.desktop/javax.swing.tree.VariableHeightLayoutCache$TreeStateNode.updatePreferredSize(VariableHeightLayoutCache.java:1344)
        at java.desktop/javax.swing.tree.VariableHeightLayoutCache.createNodeAt(VariableHeightLayoutCache.java:767)
        at java.desktop/javax.swing.tree.VariableHeightLayoutCache.treeNodesInserted(VariableHeightLayoutCache.java:476)
        at java.desktop/javax.swing.plaf.basic.BasicTreeUI$Handler.treeNodesInserted(BasicTreeUI.java:4368)
        at java.desktop/javax.swing.tree.DefaultTreeModel.fireTreeNodesInserted(DefaultTreeModel.java:553)
        at java.desktop/javax.swing.tree.DefaultTreeModel.nodesWereInserted(DefaultTreeModel.java:340)
        at java.desktop/javax.swing.tree.DefaultTreeModel.insertNodeInto(DefaultTreeModel.java:260)
        at java.base/jdk.internal.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:167)
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:102)
        at more_speech.ui.swing.article_tree$add_event.invokeStatic(article_tree.clj:178)
        at more_speech.ui.swing.article_tree$add_event.invoke(article_tree.clj:162)
        at more_speech.ui.swing.main_window.seesawHandler$fn__13969.invoke(main_window.clj:18)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:667)
        at clojure.core$apply.invoke(core.clj:662)
        at seesaw.invoke$invoke_now_STAR_$invoker__9517.invoke(invoke.clj:18)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
get-references bad-tags-in-event "For input string: \" w\" under radix 16" {:id 88220076065142523105869859183324839144438054313557800230653465849242646407794N, :pubkey 57464772279253673464534112777312873181190448684396764866967649101168459806043N, :created-at 1661461518, :kind 1, :content "Sim... Ú minha foto, nome de usußrio e bio padrÒo que eu sempre uso.\n\n\\>iamcais<\n\n???", :sig 13303546906887735035786097358520626636046522287918117819870018148662559100155210279256909851823822476984618645068200457810174673017349423698417366892563782N, :tags ((:r "boltfun Story_comment 63") (:e "269bd814f828e0126ee1e7e70eaec05412230619a2f49b4ef15ccab271931ba1 wss://nostr.drss.io reply")), :relays ["wss://relay.damus.io"]}`

**Comment by unclebob** [comment]
Yeah, boltfun sends invalid events.  I print the warning but the client should keep running.  Did it?
