### ISSUE TITLE
The app starts but loads nothing

### ISSUE THREAD

**Issue by MorKaragh** [unclebob/more-speech#31]
Hello!

I have cloned the repo, started the app with "lein run", the GUI appears but then nothing happens.
The "all" tab is empty, and it looks like nothing is happening.

Perhaps, the "connection-time-out" is the reason, but what can I do with this? 

Also, when I click with right button on the screen the NPE stacktrace is thrown in the terminal.
My OS is Ubuntu 22.04.1 LTS

```
lein run
connection-time-out "wss://nostr-pub.wellorder.net"
relay-connection-attempts-complete
requesting-contact-lists
subscription-date 1670351102 "12/07/2022 24:25:02 KGT"
open "wss://nostr-pub.wellorder.net"
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:426)
	at more_speech.ui.swing.article_tree$mouse_pressed.invokeStatic(article_tree.clj:75)
	at more_speech.ui.swing.article_tree$mouse_pressed.invoke(article_tree.clj:71)
	at seesaw.event$fire.invokeStatic(event.clj:263)
	at seesaw.event$fire.invoke(event.clj:262)
	at seesaw.event$eval12498$fn$reify__12500.mousePressed(event.clj:290)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at seesaw.core.proxy$javax.swing.JTree$Tag$fd407141.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at seesaw.core.proxy$javax.swing.JTree$Tag$fd407141.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by unclebob** [comment]
Thus is often due to a VPN blocking the websocket connections. Sent from my iPhoneOn Dec 7, 2022, at 12:33, PSVM ***@***.***> wrote:﻿
Hello!
I have cloned the repo, started the app with "lein run", the GUI appears but then nothing happens.
The "all" tab is empty, and it looks like nothing is happening.
Also, when I click with right button on the screen the NPE stacktrace is thrown in the terminal.
My OS is Ubuntu 22.04.1 LTS
`
lein run
connection-time-out "wss://nostr-pub.wellorder.net"
relay-connection-attempts-complete
requesting-contact-lists
subscription-date 1670351102 "12/07/2022 24:25:02 KGT"
open "wss://nostr-pub.wellorder.net"
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:426)
at more_speech.ui.swing.article_tree$mouse_pressed.invokeStatic(article_tree.clj:75)
at more_speech.ui.swing.article_tree$mouse_pressed.invoke(article_tree.clj:71)
at seesaw.event$fire.invokeStatic(event.clj:263)
at seesaw.event$fire.invoke(event.clj:262)
at seesaw.event$eval12498$fn$reify__12500.mousePressed(event.clj:290)
at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
at seesaw.core.proxy$javax.swing.JTree$Tag$fd407141.processMouseEvent(Unknown Source)
at java.desktop/java.awt.Component.processEvent(Component.java:6400)
at java.desktop/java.awt.Container.processEvent(Container.java:2263)
at seesaw.core.proxy$javax.swing.JTree$Tag$fd407141.processEvent(Unknown Source)
at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4544)
at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
at java.base/java.security.AccessController.doPrivileged(Native Method)
at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
`

**Comment by MorKaragh** [comment]
That's wierd. 
I don't have any VPN connected.

**Comment by unclebob** [comment]
Have you tried using a different relay?  There are a lot of them out there now.  Look at http://nostr.watch.

**Comment by Perlover** [comment]
+1
Compiled, launched. A tabbed window opened. There are only buttons: Back / Reply / Create / Forward and Tabs: Messages / Relays and follow / all

It is unclear where to enter your key, where to create a key if there is none. I didn't understand anything. Apparently this is some kind of developer debugging tool. It is strange to see so many "stars" and there are few "issues", and even more so to see a broken program.

**Comment by unclebob** [comment]
The wiki should explain where to enter your key.  It's in the private/keys file.  The first run of the program will create a public and priavate key for you and load them into the private/keys file if you haven't put them in there already.  

The private/relays file shows the relays you are reading from and writing to.  Older versions initialized this to wellorder.net but I think that relay is non-functional now.  Later versions updated this to a batch of relays that should provide some events.

The "all" tab ought to show you some events within a few minutes.   If you want to see a higher volume of events then change the private/relays file so that some of the :read-trusted relays are :read-all.  Beware you can get a LOT of events that way.

The best way to proceed after that is to subscribe to a good paid relay like eden.nostr.land, and set the relay to :read-all .  This will give you a lot of events, but keep most of the spam out.  From there you can start trusting people and setting up tabs.
