### ISSUE TITLE
java.lang.NumberFormatException when trying to run on Arch linux

### ISSUE THREAD

**Issue by SeaEagle568** [unclebob/more-speech#36]
The application does not start - the error report is the following:
```{:clojure.main/message
 "Execution error (NumberFormatException) at java.lang.NumberFormatException/forInputString (NumberFormatException.java:67).\nFor input string: \"JTree\"\n",
 :clojure.main/triage
 {:clojure.error/class java.lang.NumberFormatException,
  :clojure.error/line 67,
  :clojure.error/cause "For input string: \"JTree\"",
  :clojure.error/symbol java.lang.NumberFormatException/forInputString,
  :clojure.error/source "NumberFormatException.java",
  :clojure.error/phase :execution},
 :clojure.main/trace
 {:via
  [{:type clojure.lang.Compiler$CompilerException,
    :message
    "Syntax error macroexpanding at (/tmp/form-init14744791229083861061.clj:1:74).",
    :data
    {:clojure.error/phase :execution,
     :clojure.error/line 1,
     :clojure.error/column 74,
     :clojure.error/source "/tmp/form-init14744791229083861061.clj"},
    :at [clojure.lang.Compiler load "Compiler.java" 7665]}
   {:type java.lang.reflect.InvocationTargetException,
    :at [java.awt.EventQueue invokeAndWait "EventQueue.java" 1371]}
   {:type java.lang.NumberFormatException,
    :message "For input string: \"JTree\"",
    :at
    [java.lang.NumberFormatException
     forInputString
     "NumberFormatException.java"
     67]}],
  :trace
  [[java.lang.NumberFormatException
    forInputString
    "NumberFormatException.java"
    67]
   [java.lang.Integer parseInt "Integer.java" 668]
   [java.math.BigInteger <init> "BigInteger.java" 536]
   [java.math.BigInteger <init> "BigInteger.java" 674]
   [jdk.internal.reflect.DirectConstructorHandleAccessor
    newInstance
    "DirectConstructorHandleAccessor.java"
    67]
   [java.lang.reflect.Constructor
    newInstanceWithCaller
    "Constructor.java"
    499]
   [java.lang.reflect.Constructor newInstance "Constructor.java" 483]
   [clojure.lang.Reflector invokeConstructor "Reflector.java" 305]
   [clojure.core$bigint invokeStatic "core.clj" 3625]
   [clojure.core$bigint invoke "core.clj" 3620]
   [more_speech.db.xtdb$get_entity invokeStatic "xtdb.clj" 61]
   [more_speech.db.xtdb$get_entity invoke "xtdb.clj" 59]
   [more_speech.db.xtdb$eval7566$fn__7567 invoke "xtdb.clj" 87]
   [clojure.lang.MultiFn invoke "MultiFn.java" 234]
   [more_speech.ui.swing.article_tree$render_event
    invokeStatic
    "article_tree.clj"
    117]
   [more_speech.ui.swing.article_tree$render_event
    invoke
    "article_tree.clj"
    112]
   [seesaw.cells$default_tree_cell_renderer$fn__19136
    invoke
    "cells.clj"
    44]
   [seesaw.cells.proxy$javax.swing.tree.DefaultTreeCellRenderer$ff19274a
    getTreeCellRendererComponent
    nil
    -1]
   [javax.swing.plaf.basic.BasicTreeUI$NodeDimensionsHandler
    getNodeDimensions
    "BasicTreeUI.java"
    3220]
   [javax.swing.tree.AbstractLayoutCache
    getNodeDimensions
    "AbstractLayoutCache.java"
    497]
   [javax.swing.tree.VariableHeightLayoutCache$TreeStateNode
    updatePreferredSize
    "VariableHeightLayoutCache.java"
    1344]
   [javax.swing.tree.VariableHeightLayoutCache
    updateNodeSizes
    "VariableHeightLayoutCache.java"
    903]
   [javax.swing.tree.VariableHeightLayoutCache
    invalidateSizes
    "VariableHeightLayoutCache.java"
    371]
   [javax.swing.plaf.basic.BasicTreeUI
    setCellRenderer
    "BasicTreeUI.java"
    475]
   [javax.swing.plaf.basic.BasicTreeUI$Handler
    propertyChange
    "BasicTreeUI.java"
    3896]
   [java.beans.PropertyChangeSupport
    fire
    "PropertyChangeSupport.java"
    343]
   [java.beans.PropertyChangeSupport
    firePropertyChange
    "PropertyChangeSupport.java"
    335]
   [java.beans.PropertyChangeSupport
    firePropertyChange
    "PropertyChangeSupport.java"
    268]
   [java.awt.Component firePropertyChange "Component.java" 8712]
   [seesaw.core.proxy$javax.swing.JTree$Tag$fd407141
    firePropertyChange
    nil
    -1]
   [javax.swing.JTree setCellRenderer "JTree.java" 827]
   [seesaw.core.proxy$javax.swing.JTree$Tag$fd407141
    setCellRenderer
    nil
    -1]
   [seesaw.core$fn__21490 invokeStatic "core.clj" 1790]
   [seesaw.core$fn__21490 invoke "core.clj" 1789]
   [seesaw.options$apply_option invokeStatic "options.clj" 114]
   [seesaw.options$apply_option invoke "options.clj" 111]
   [seesaw.options$apply_options_STAR_ invokeStatic "options.clj" 129]
   [seesaw.options$apply_options_STAR_ invoke "options.clj" 124]
   [seesaw.options$apply_options invokeStatic "options.clj" 136]
   [seesaw.options$apply_options invoke "options.clj" 132]
   [seesaw.core$tree invokeStatic "core.clj" 1815]
   [seesaw.core$tree doInvoke "core.clj" 1805]
   [clojure.lang.RestFn invoke "RestFn.java" 619]
   [more_speech.ui.swing.article_tree$make_header_tree
    invokeStatic
    "article_tree.clj"
    125]
   [more_speech.ui.swing.article_tree$make_header_tree
    invoke
    "article_tree.clj"
    124]
   [more_speech.ui.swing.tabs$make_tabs invokeStatic "tabs.clj" 58]
   [more_speech.ui.swing.tabs$make_tabs invoke "tabs.clj" 50]
   [more_speech.ui.swing.main_window$make_main_window
    invokeStatic
    "main_window.clj"
    51]
   [more_speech.ui.swing.main_window$make_main_window
    invoke
    "main_window.clj"
    43]
   [more_speech.ui.swing.main_window$setup_main_window$fn__22696
    invoke
    "main_window.clj"
    81]
   [clojure.lang.AFn applyToHelper "AFn.java" 152]
   [clojure.lang.AFn applyTo "AFn.java" 144]
   [clojure.core$apply invokeStatic "core.clj" 667]
   [clojure.core$apply invoke "core.clj" 662]
   [seesaw.invoke$invoke_now_STAR_$invoker__17422
    invoke
    "invoke.clj"
    18]
   [clojure.lang.AFn run "AFn.java" 22]
   [java.awt.event.InvocationEvent dispatch "InvocationEvent.java" 308]
   [java.awt.EventQueue dispatchEventImpl "EventQueue.java" 773]
   [java.awt.EventQueue$4 run "EventQueue.java" 720]
   [java.awt.EventQueue$4 run "EventQueue.java" 714]
   [java.security.AccessController
    doPrivileged
    "AccessController.java"
    399]
   [java.security.ProtectionDomain$JavaSecurityAccessImpl
    doIntersectionPrivilege
    "ProtectionDomain.java"
    86]
   [java.awt.EventQueue dispatchEvent "EventQueue.java" 742]
   [java.awt.EventDispatchThread
    pumpOneEventForFilters
    "EventDispatchThread.java"
    203]
   [java.awt.EventDispatchThread
    pumpEventsForFilter
    "EventDispatchThread.java"
    124]
   [java.awt.EventDispatchThread
    pumpEventsForHierarchy
    "EventDispatchThread.java"
    113]
   [java.awt.EventDispatchThread
    pumpEvents
    "EventDispatchThread.java"
    109]
   [java.awt.EventDispatchThread
    pumpEvents
    "EventDispatchThread.java"
    101]
   [java.awt.EventDispatchThread run "EventDispatchThread.java" 90]],
  :cause "For input string: \"JTree\"",
  :phase :execution}}
```

I've installed openjdk-17, as well as clojure and leiningen using pacman on Arch linux.
I've cloned a repository and run a command 
`lein run project.clj` in fish shell.
The output of the command is following:
```
Compiling 7 source files to /home/username/Apps/more-speech/target/classes
main "project.clj" start
main loading-configuration
main setting-up-gui
make-main-window
make-main-window making-article-area
Execution error (NumberFormatException) at java.lang.NumberFormatException/forInputString (NumberFormatException.java:67).
For input string: "JTree"

```
I've also tried downloading a pre-built artifact and running it via java -jar but there is a different error message:
```java -jar more-speech-0.1.0-SNAPSHOT-standalone.jar
Exception in thread "main" java.lang.Exception: Attempting to migrate from level 10 to 9.
	at more_speech.migrator$get_needed_migrations.invokeStatic(migrator.clj:153)
	at more_speech.migrator$get_needed_migrations.invoke(migrator.clj:150)
	at more_speech.migrator$migrate_to.invokeStatic(migrator.clj:158)
	at more_speech.migrator$migrate_to.invoke(migrator.clj:157)
	at more_speech.core$_main.invokeStatic(core.clj:26)
	at more_speech.core$_main.doInvoke(core.clj:25)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at more_speech.core.main(Unknown Source)```

**Comment by unclebob** [comment]
Hmmm.  Look at line 117 of article-tree.  The event-id should be an integer but it's "JTree".  That's strange because the string JTree is nowhere in the code.  I presume it's coming from some UBUNTU shim for one of the frameworks like seesaw.

Try this.  After line 116 which gets the event-id from the user object in the node, check to see if the event-id is a number.  If not, set it to 0.  

So right after line 116 add:
event-id (if (num? event-id) event-id 0)

Let me know if that works.

**Comment by shyamkovuri3** [comment]
> Hmmm. Look at line 117 of article-tree. The event-id should be an integer but it's "JTree". That's strange because the string JTree is nowhere in the code. I presume it's coming from some UBUNTU shim for one of the frameworks like seesaw.
> 
> Try this. After line 116 which gets the event-id from the user object in the node, check to see if the event-id is a number. If not, set it to 0.
> 
> So right after line 116 add: event-id (if (num? event-id) event-id 0)
> 
> Let me know if that works.

it works after add this check, on ubuntu
event-id (if (number? event-id) event-id 0)

**Comment by honza** [comment]
I get this with latest master:

```
$ lein run
main nil start
main loading-configuration
main setting-up-gui
make-main-window
make-main-window making-article-area
Execution error (NumberFormatException) at java.lang.NumberFormatException/forInputString (NumberFormatException.java:67).
For input string: "JTree"

Full report at:
/tmp/clojure-8450093327073827219.edn
```

**Comment by mukadr** [comment]
Same issue on Windows 10.

```
PS C:\Projects\more-speech> lein run
main nil start
main loading-configuration
main setting-up-gui
make-main-window
make-main-window making-article-area
Execution error (NumberFormatException) at java.lang.NumberFormatException/forInputString (NumberFormatException.java:67).
For input string: "JTree"

Full report at:
C:\Users\mukad\AppData\Local\Temp\clojure-11097469703171794106.edn
```

**Comment by unclebob** [comment]
OK, I'll put that line in.  I still can't imagine where the "JTree" string is coming from.  It's nowhere in my source code.  And the UserObject ought to be set to zero.  BTW, the migrator problem you had with the jar file was probably due to you running in in the same directory as the others.  The file private/migration was probably set to 10.  

To get that jar file to work, start it up in a clean directory.

**Comment by mukadr** [comment]
Problem solved!

Thanks.
